name: checkit
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  
  flutter:
    sdk: flutter
  http: 0.13.0
  path_provider: ^2.0.0

  cupertino_icons: ^1.0.2

  cloud_firestore: ^3.1.5
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.2

  indexed: ^0.0.8
  json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  pie_chart: ^5.3.2

flutter_icons:
  android: true
  ios: true
  image_path: assets/img/test-app-icon.png

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/img/mewithoutbackground.png
    - assets/img/mewithbackground.png
    - assets/img/try.png
    - assets/img/try2.jpg
    - assets/img/try3.jpg
    - assets/img/try4.png
    - assets/img/try5.png
    - assets/img/try6.png
    - assets/img/try7.png
    - assets/img/try8.jpeg
    - assets/img/try9.jpeg
    - assets/img/try10.jpeg
    - assets/img/try11.jpeg
    - assets/img/try12.png
    - assets/img/try13.png
    - assets/img/try14.png
    - assets/img/try15.png
    - assets/img/try16.png
    - assets/img/try17.png
    - assets/img/try18.png
 
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotMono/RobotoMono-Bold.ttf
    - family: BeautifulEveryTime
      fonts:
        - asset: assets/fonts/BeautifulEveryTime/BeautifulEveryTime-Dg4m.ttf
    - family: ShadowsIntoLight
      fonts:
        - asset: assets/fonts/ShadowsIntoLight/ShadowsIntoLight-Regular.ttf
    - family: Aptos
      fonts:
        - asset: assets/fonts/Aptos/Aptos.ttf
       
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
